apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: satishmp45/jktech-backend-public:latest
          ports:
            - containerPort: 3000
          env:
            #  secret/database-secret
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: database-secret
                  key: DATABASE_URL 

            # oauth credentials from secret/oauth-cred

            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: oauth-cred
                  key: JWT_SECRET

            - name: GOOGLE_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: oauth-cred
                  key: GOOGLE_CLIENT_ID

            - name: GOOGLE_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: oauth-cred
                  key: GOOGLE_CLIENT_SECRET

            - name: GOOGLE_CALLBACK_URL
              valueFrom:
                secretKeyRef:
                  name: oauth-cred
                  key: GOOGLE_CALLBACK_URL 

            - name: FACEBOOK_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: oauth-cred
                  key: FACEBOOK_CLIENT_ID

            - name: FACEBOOK_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: oauth-cred
                  key: FACEBOOK_CLIENT_SECRET

            - name: FACEBOOK_CALLBACK_URL
              valueFrom:
                secretKeyRef:
                  name: oauth-cred
                  key: FACEBOOK_CALLBACK_URL 

            # configuration from configmap/config-env
            - name: NODE_ENV
              valueFrom:
                configMapKeyRef:
                  name: config-env
                  key: NODE_ENV
                  
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: config-env
                  key: PORT

            - name: JWT_EXPIRY
              valueFrom:
                configMapKeyRef:
                  name: config-env
                  key: JWT_EXPIRY
          command: ["sh", "./start.sh"]
