
services:
  backend:
    build: .
    environment:
      - DATABASE_URL=postgresql://postgres:Satish@456@postgres:5432/jk-tech
    container_name: jktech-backend
    restart: unless-stopped
    ports:
      - '3000:3000'
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules 
    depends_on:
      - postgres
    command: ["./start.sh"]

  postgres:
    image: postgres:15
    container_name: jktech-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Satish@456
      POSTGRES_DB: jk-tech
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
